-- begin JOKERAPP_PRODUCT_ITEM
alter table JOKERAPP_PRODUCT_ITEM add constraint FK_JOKERAPP_PRODUCT_ITEM_CATEGORY foreign key (CATEGORY_ID) references JOKERAPP_PRODUCT_ITEM_CATEGORY(ID)^
create index IDX_JOKERAPP_PRODUCT_ITEM_CATEGORY on JOKERAPP_PRODUCT_ITEM (CATEGORY_ID)^
-- end JOKERAPP_PRODUCT_ITEM
-- begin JOKERAPP_TABLE_ITEM
alter table JOKERAPP_TABLE_ITEM add constraint FK_JOKERAPP_TABLE_ITEM_AREA foreign key (AREA_ID) references JOKERAPP_TABLE_ITEM_AREA(ID)^
create index IDX_JOKERAPP_TABLE_ITEM_AREA on JOKERAPP_TABLE_ITEM (AREA_ID)^
-- end JOKERAPP_TABLE_ITEM
-- begin JOKERAPP_TICKET_ITEM_LINE
alter table JOKERAPP_TICKET_ITEM_LINE add constraint FK_JOKERAPP_TICKET_ITEM_LINE_PRODUCT_ITEM foreign key (PRODUCT_ITEM_ID) references JOKERAPP_PRODUCT_ITEM(ID)^
create index IDX_JOKERAPP_TICKET_ITEM_LINE_PRODUCT_ITEM on JOKERAPP_TICKET_ITEM_LINE (PRODUCT_ITEM_ID)^
-- end JOKERAPP_TICKET_ITEM_LINE
-- begin JOKERAPP_PRODUCT_MODIFIER
alter table JOKERAPP_PRODUCT_MODIFIER add constraint FK_JOKERAPP_PRODUCT_MODIFIER_CATEGORY foreign key (CATEGORY_ID) references JOKERAPP_PRODUCT_MODIFIER_CATEGORY(ID)^
create index IDX_JOKERAPP_PRODUCT_MODIFIER_CATEGORY on JOKERAPP_PRODUCT_MODIFIER (CATEGORY_ID)^
-- end JOKERAPP_PRODUCT_MODIFIER
