-- begin JOKERAPP_PRODUCT_ITEM
alter table JOKERAPP_PRODUCT_ITEM add constraint FK_JOKERAPP_PRODUCT_ITEM_CATEGORY foreign key (CATEGORY_ID) references JOKERAPP_PRODUCT_CATEGORY(ID)^
create index IDX_JOKERAPP_PRODUCT_ITEM_CATEGORY on JOKERAPP_PRODUCT_ITEM (CATEGORY_ID)^
-- end JOKERAPP_PRODUCT_ITEM
