alter table JOKERAPP_ORDER add constraint FK_JOKERAPP_ORDER_ON_TABLE_ITEM foreign key (TABLE_ITEM_ID) references JOKERAPP_TABLE_ITEM(ID);
create index IDX_JOKERAPP_ORDER_ON_TABLE_ITEM on JOKERAPP_ORDER (TABLE_ITEM_ID);
