alter table JOKERAPP_TABLE_ITEM add constraint FK_JOKERAPP_TABLE_ITEM_ON_CURRENT_ORDER foreign key (CURRENT_ORDER_ID) references JOKERAPP_ORDER(ID);
create index IDX_JOKERAPP_TABLE_ITEM_ON_CURRENT_ORDER on JOKERAPP_TABLE_ITEM (CURRENT_ORDER_ID);
