alter table JOKERAPP_TABLE_ITEM add constraint FK_JOKERAPP_TABLE_ITEM_TABLE_AREA foreign key (TABLE_AREA_ID) references JOKERAPP_TABLE_ITEM_AREA(ID);
create index IDX_JOKERAPP_TABLE_ITEM_TABLE_AREA on JOKERAPP_TABLE_ITEM (TABLE_AREA_ID);
