alter table JOKERAPP_ORDER add constraint FK_JOKERAPP_ORDER_WAITER_CALL_USER foreign key (WAITER_CALL_USER_ID) references JOKERAPP_USER(ID);
create index IDX_JOKERAPP_ORDER_WAITER_CALL_USER on JOKERAPP_ORDER (WAITER_CALL_USER_ID);
