alter table JOKERAPP_TABLE_ITEM add constraint FK_JOKERAPP_TABLE_ITEM_AREA foreign key (AREA_ID) references JOKERAPP_TABLE_ITEM_AREA(ID);
create index IDX_JOKERAPP_TABLE_ITEM_AREA on JOKERAPP_TABLE_ITEM (AREA_ID);
