alter table JOKERAPP_TICKET_ITEM add constraint FK_JOKERAPP_TICKET_ITEM_TABLE_ITEM foreign key (TABLE_ITEM_ID) references JOKERAPP_TABLE_ITEM(ID);
create index IDX_JOKERAPP_TICKET_ITEM_TABLE_ITEM on JOKERAPP_TICKET_ITEM (TABLE_ITEM_ID);
