alter table JOKERAPP_TABLE_ITEM rename to JOKERAPP_TABLE_ITEM__UNUSED ;
alter table JOKERAPP_TICKET_ITEM drop constraint FK_JOKERAPP_TICKET_ITEM_TABLE_ITEM ;
alter table JOKERAPP_TICKET drop constraint FK_JOKERAPP_TICKET_TABLE_ITEM ;
