alter table JOKERAPP_TICKET add constraint FK_JOKERAPP_TICKET_TABLE_ITEM foreign key (TABLE_ITEM_ID) references JOKERAPP_TABLE_ITEM(ID);
create index IDX_JOKERAPP_TICKET_TABLE_ITEM on JOKERAPP_TICKET (TABLE_ITEM_ID);
