alter table JOKERAPP_TICKET add constraint FK_JOKERAPP_TICKET_PRODUCT_ITEM foreign key (PRODUCT_ITEM_ID) references JOKERAPP_PRODUCT_ITEM(ID);
create index IDX_JOKERAPP_TICKET_PRODUCT_ITEM on JOKERAPP_TICKET (PRODUCT_ITEM_ID);
