alter table JOKERAPP_ORDER add constraint FK_JOKERAPP_ORDER_TABLE_NUMBER foreign key (TABLE_NUMBER_ID) references JOKERAPP_TABLE_ITEM(ID);
create index IDX_JOKERAPP_ORDER_TABLE_NUMBER on JOKERAPP_ORDER (TABLE_NUMBER_ID);
