alter table JOKERAPP_ORDER add constraint FK_JOKERAPP_ORDER_ORDER_ID foreign key (ORDER_ID_ID) references JOKERAPP_TABLE_ITEM(ID);
create index IDX_JOKERAPP_ORDER_ORDER_ID on JOKERAPP_ORDER (ORDER_ID_ID);
