-- begin JOKERAPP_PRODUCT_ITEM
alter table JOKERAPP_PRODUCT_ITEM add constraint FK_JOKERAPP_PRODUCT_ITEM_ON_CATEGORY foreign key (CATEGORY_ID) references JOKERAPP_PRODUCT_ITEM_CATEGORY(ID)^
create index IDX_JOKERAPP_PRODUCT_ITEM_ON_CATEGORY on JOKERAPP_PRODUCT_ITEM (CATEGORY_ID)^
-- end JOKERAPP_PRODUCT_ITEM
-- begin JOKERAPP_PRODUCT_MODIFIER
alter table JOKERAPP_PRODUCT_MODIFIER add constraint FK_JOKERAPP_PRODUCT_MODIFIER_ON_CATEGORY foreign key (CATEGORY_ID) references JOKERAPP_PRODUCT_MODIFIER_CATEGORY(ID)^
create index IDX_JOKERAPP_PRODUCT_MODIFIER_ON_CATEGORY on JOKERAPP_PRODUCT_MODIFIER (CATEGORY_ID)^
-- end JOKERAPP_PRODUCT_MODIFIER

-- begin JOKERAPP_TABLE_ITEM
alter table JOKERAPP_TABLE_ITEM add constraint FK_JOKERAPP_TABLE_ITEM_ON_CURRENT_ORDER foreign key (CURRENT_ORDER_ID) references JOKERAPP_ORDER(ID)^
create unique index IDX_JOKERAPP_TABLE_ITEM_UK_TABLE_NUMBER on JOKERAPP_TABLE_ITEM (TABLE_NUMBER) where DELETE_TS is null ^
create unique index IDX_JOKERAPP_TABLE_ITEM_UK_CURRENT_ORDER_ID on JOKERAPP_TABLE_ITEM (CURRENT_ORDER_ID) where DELETE_TS is null ^
create index IDX_JOKERAPP_TABLE_ITEM_ON_CURRENT_ORDER on JOKERAPP_TABLE_ITEM (CURRENT_ORDER_ID)^
-- end JOKERAPP_TABLE_ITEM
-- begin JOKERAPP_ORDER_LINE
alter table JOKERAPP_ORDER_LINE add constraint FK_JOKERAPP_ORDER_LINE_ON_ORDER foreign key (ORDER_ID) references JOKERAPP_ORDER(ID)^
create index IDX_JOKERAPP_ORDER_LINE_ON_ORDER on JOKERAPP_ORDER_LINE (ORDER_ID)^
-- end JOKERAPP_ORDER_LINE
-- begin JOKERAPP_PRODUCT_ITEM_PRODUCT_MODIFIER_CATEGORY_LINK
alter table JOKERAPP_PRODUCT_ITEM_PRODUCT_MODIFIER_CATEGORY_LINK add constraint FK_PROITEPROMODCAT_ON_PRODUCT_MODIFIER_CATEGORY foreign key (PRODUCT_MODIFIER_CATEGORY_ID) references JOKERAPP_PRODUCT_MODIFIER_CATEGORY(ID)^
alter table JOKERAPP_PRODUCT_ITEM_PRODUCT_MODIFIER_CATEGORY_LINK add constraint FK_PROITEPROMODCAT_ON_PRODUCT_ITEM foreign key (PRODUCT_ITEM_ID) references JOKERAPP_PRODUCT_ITEM(ID)^
-- end JOKERAPP_PRODUCT_ITEM_PRODUCT_MODIFIER_CATEGORY_LINK
