-- begin JOKERAPP_PRODUCT_ITEM
alter table JOKERAPP_PRODUCT_ITEM add constraint FK_JOKERAPP_PRODUCT_ITEM_ON_CATEGORY foreign key (CATEGORY_ID) references JOKERAPP_PRODUCT_ITEM_CATEGORY(ID)^
create index IDX_JOKERAPP_PRODUCT_ITEM_ON_CATEGORY on JOKERAPP_PRODUCT_ITEM (CATEGORY_ID)^
-- end JOKERAPP_PRODUCT_ITEM
-- begin JOKERAPP_PRODUCT_MODIFIER
alter table JOKERAPP_PRODUCT_MODIFIER add constraint FK_JOKERAPP_PRODUCT_MODIFIER_ON_CATEGORY foreign key (CATEGORY_ID) references JOKERAPP_PRODUCT_MODIFIER_CATEGORY(ID)^
create index IDX_JOKERAPP_PRODUCT_MODIFIER_ON_CATEGORY on JOKERAPP_PRODUCT_MODIFIER (CATEGORY_ID)^
-- end JOKERAPP_PRODUCT_MODIFIER
-- begin JOKERAPP_ORDER
alter table JOKERAPP_ORDER add constraint FK_JOKERAPP_ORDER_ON_TABLE_ITEM foreign key (TABLE_ITEM_ID) references JOKERAPP_TABLE_ITEM(ID)^
create index IDX_JOKERAPP_ORDER_ON_TABLE_ITEM on JOKERAPP_ORDER (TABLE_ITEM_ID)^
-- end JOKERAPP_ORDER
-- begin JOKERAPP_TABLE_ITEM
create unique index IDX_JOKERAPP_TABLE_ITEM_UK_TABLE_NUMBER on JOKERAPP_TABLE_ITEM (TABLE_NUMBER) where DELETE_TS is null ^
-- end JOKERAPP_TABLE_ITEM
-- begin JOKERAPP_ORDER_LINE
alter table JOKERAPP_ORDER_LINE add constraint FK_JOKERAPP_ORDER_LINE_ON_ORDER foreign key (ORDER_ID) references JOKERAPP_ORDER(ID)^
alter table JOKERAPP_ORDER_LINE add constraint FK_JOKERAPP_ORDER_LINE_ON_PRODUCT_ITEM foreign key (PRODUCT_ITEM_ID) references JOKERAPP_PRODUCT_ITEM(ID)^
create index IDX_JOKERAPP_ORDER_LINE_ON_ORDER on JOKERAPP_ORDER_LINE (ORDER_ID)^
create index IDX_JOKERAPP_ORDER_LINE_ON_PRODUCT_ITEM on JOKERAPP_ORDER_LINE (PRODUCT_ITEM_ID)^
-- end JOKERAPP_ORDER_LINE
