alter table SEC_ROLE rename column default_specific_access to default_specific_access__u34682 ;
alter table SEC_ROLE rename column default_entity_attr_access to default_entity_attr_access__u79740 ;
alter table SEC_ROLE rename column default_entity_delete_access to default_entity_delete_access__u17720 ;
alter table SEC_ROLE rename column default_entity_update_access to default_entity_update_access__u54014 ;
alter table SEC_ROLE rename column default_entity_read_access to default_entity_read_access__u01209 ;
alter table SEC_ROLE rename column default_entity_create_access to default_entity_create_access__u07781 ;
alter table SEC_ROLE rename column default_screen_access to default_screen_access__u86057 ;
