alter table JOKERAPP_PRODUCT_ITEM add constraint FK_JOKERAPP_PRODUCT_ITEM_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID);
create index IDX_JOKERAPP_PRODUCT_ITEM_IMAGE on JOKERAPP_PRODUCT_ITEM (IMAGE_ID);
