alter table JOKERAPP_ORDER_LINE add constraint FK_JOKERAPP_ORDER_LINE_ON_TICKET foreign key (TICKET_ID) references JOKERAPP_TICKET(ID);
create index IDX_JOKERAPP_ORDER_LINE_ON_TICKET on JOKERAPP_ORDER_LINE (TICKET_ID);
